// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxeM0c36szz8vCsuGyEgUBX6OEAwIRCs0',
    appId: '1:380398403730:web:1da5846c16d3a9bfcba64b',
    messagingSenderId: '380398403730',
    projectId: 'flutterfire-ui-codelab-ac886',
    authDomain: 'flutterfire-ui-codelab-ac886.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-ac886.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQGAV5xrMkY6WPD4ZgA1VkH7aA_W2tmRY',
    appId: '1:380398403730:android:91f07238a1d542dacba64b',
    messagingSenderId: '380398403730',
    projectId: 'flutterfire-ui-codelab-ac886',
    storageBucket: 'flutterfire-ui-codelab-ac886.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWAXpfpWykkkjhYo3zLVIW3o5OMvmZv4Y',
    appId: '1:380398403730:ios:fcc70f9dd742e188cba64b',
    messagingSenderId: '380398403730',
    projectId: 'flutterfire-ui-codelab-ac886',
    storageBucket: 'flutterfire-ui-codelab-ac886.appspot.com',
    iosClientId: '380398403730-ro525pm0p8najd1d8gohgfm4lk19b1aa.apps.googleusercontent.com',
    iosBundleId: 'com.example.step02',
  );
}
